export const FUTURE_EVENTS =[
  {
    date: 'September 4th, 2024',
    slug: 'tbd-hoboken-september-4',
    title: 'TBD',
    description: 'TBD',
    location: 'Tenth Street Pasta and Pizza - 1000 Willow Ave (corner of 10th & Willow) Hoboken, NJ',
    state: 'NJ',
    mainImage: '',
    thumbnails: [],
    videos: [],
  },
  {
    date: 'September 10th, 2024',
    slug: 'tbd-nyc-september-10',
    title: 'TBD',
    description: 'TBD',
    location: 'Bareburger, 366 W 46th St, New York, NY 10036, USA',
    state: 'NY',
    mainImage: '',
    thumbnails: [],
    videos: [],
  },
  {
    date: 'September 11th, 2024',
    slug: 'tbd-hoboken-september-11',
    title: 'TBD',
    description: 'TBD',
    location: 'Tenth Street Pasta and Pizza - 1000 Willow Ave (corner of 10th & Willow) Hoboken, NJ',
    state: 'NJ',
    mainImage: '',
    thumbnails: [],
    videos: [],
  },
  {
    date: 'September 17th, 2024',
    slug: 'tbd-nyc-september-17',
    title: 'TBD',
    description: 'TBD',
    location: 'Bareburger, 366 W 46th St, New York, NY 10036, USA',
    state: 'NY',
    mainImage: '',
    thumbnails: [],
    videos: [],
  },
] 